name: Build and push Bento Service-Registry image
on:
  workflow_dispatch:

env:
  TAG: v0.6.0

jobs:
  build-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up image metadata for service-registry-alpine
        id: meta-service-registry-alpine
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/bento-platform/bento_image
          tags: |
            type=raw,value=service-registry-${{ env.TAG }}-alpine-latest
            type=raw,value=service-registry-${{ env.TAG }}-alpine-{{date 'YYYY.MM.DD'}}
            type=raw,value=service-registry-${{ env.TAG }}-alpine-{{date 'YYYY.MM.DD.HHmm'}}

      - name: Build and push service-registry-alpine image
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ./spec/service-registry/alpine.Dockerfile
          context: ./spec/service-registry
          build-args: |
            TAG=${{ env.TAG }}
          tags: ${{ steps.meta-service-registry-alpine.outputs.tags }}
          labels: ${{ steps.meta-service-registry-alpine.outputs.labels }}
          platforms: linux/arm64,linux/amd64

